# Generated by Django 4.2 on 2023-04-18 10:09

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_alter_asset_description_alter_asset_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=10)),
                ('open_price', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=10)),
                ('previous_close', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20)),
                ('change', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7)),
                ('percent_change', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
        ),
    ]
