# Generated by Django 4.2 on 2023-04-18 10:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='change',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='price',
            name='close_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='high_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='low_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='open_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='percent_change',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='price',
            name='previous_close',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=10),
        ),
    ]
