# Generated by Django 4.2 on 2023-04-19 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='volume',
        ),
        migrations.AddField(
            model_name='trade',
            name='quantity',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
