# Generated by Django 4.2 on 2023-04-20 08:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='execution_price',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=10),
        ),
    ]
